config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get '/auth/:provider/callback', to: 'sessions#create', as: :callback
  resources :upload, only: [:index]
  get 'welcome/index'
  get 'sessions/logout'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/upload.rb
class Upload
  # http://blog.isnorcreative.com/2014/05/08/easier-non-activerecord-models-in-rails-4.html
  # http://blog.remarkablelabs.com/2012/12/activemodel-model-rails-4-countdown-to-2013
  include ActiveModel::Model

  attr_accessor :form_action
  attr_accessor :key
  attr_accessor :prefix
  attr_accessor :acl
  attr_accessor :policy_text
  attr_accessor :success_action_redirect

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # provider: amazon
    # uid: amzn1.account.AGR73NTZDPH5ZPIG4IUIISP2R4WQ
    # info: !ruby/hash:OmniAuth::AuthHash::InfoHash
    #   email: russell.sayers@gmail.com
    #   name: Russell Sayers
    # credentials: !ruby/hash:OmniAuth::AuthHash
    #   token: xxxx
    #   refresh_token: xxxx
    #   expires_at: 1424576601
    #   expires: true
    # extra: !ruby/hash:OmniAuth::AuthHash
    #   postal_code:

    # users cannot tamper with session cookie, safe to store auth info in here
    # (so long as secrets.yml is secret!)
    # http://guides.rubyonrails.org/security.html


    auth = request.env['omniauth.auth']
    session[:user_id] = auth.info.email
    session[:token] = auth.credentials.token
    session[:uid] = auth.uid

    logger.info("#{auth.to_yaml}")
    current_user = User.find_by_uid(auth.uid);
    if (current_user.nil?)
      logger.info("user not found #{auth.uid}, creating...")
      user = User.create(uid:auth.uid, email:auth.info.email, name:auth.info.name)
    end

    flash[:notice] = "Welcome back"
    redirect_to '/'
  end

  def logout
    reset_session
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def index
    @upload = Upload.new
    @upload.form_action = "https://s3.amazonaws.com/sayersr-demos-uploads/"
    @upload.key = "uploads/#{session[:uid]}/${filename}"
    @upload.prefix = "uploads/#{session[:uid]}/"
    @upload.acl = "private"
    @upload.success_action_redirect = upload_index_url
    @upload.policy_text = '{"expiration": "2016-01-01T00:00:00Z", "conditions":
    [ {"bucket": "sayersr-demos-uploads"}, ["starts-with", "$key", "uploads/'+session[:uid]+'/"], {"acl": "private"},
    {"success_action_redirect": "' + upload_index_url + '"},
    ["starts-with", "$x-amz-security-token", ""], ["content-length-range", 0, 1048000] ] }'

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://sdk.amazonaws.com/js/aws-sdk-2.1.12.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= nav_bar :static => :top, brand: "Demo Portal", responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", welcome_index_path %>
        <%= menu_item "Upload", upload_index_path %>

    <% end %>
    <%= menu_group :pull => :right do %>
        <% !if session[:user_id].nil?  %>
            <%= menu_item "Log Out", sessions_logout_path %>
            <%= menu_item session[:user_id] , "#" %>
        <% end %>
    <% end %>
<% end %>

<div class="container theme-showcase" role="main">
<%= bootstrap_flash %>

<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

    <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            posts_path, :class => 'btn btn-default' %>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/upload/index.html.erb
<h1>Uploader</h1>

<ul id="files">
</ul>

<form action="https://s3.amazonaws.com/sayersr-demos-uploads/" method="post" enctype="multipart/form-data">
  <%= hidden_field_tag(:AWSAccessKeyId) %>
  <%= hidden_field_tag(:key, @upload.key) %>
  <%= hidden_field_tag(:acl, @upload.acl) %>
  <%= hidden_field_tag(:success_action_redirect, @upload.success_action_redirect) %>
  <%= hidden_field_tag(:policy, Base64.strict_encode64(@upload.policy_text)) %>
  <%= hidden_field_tag(:signature) %>
  <%= hidden_field_tag("x-amz-security-token") %>
  <input name="file" type="file">
  <input type="submit" value="Upload File to S3">
</form>

<script>
  <% if !session[:token].nil? %>
  var params = {
    RoleArn: 'arn:aws:iam::612895797421:role/ExtraTimeWebIdentity', /* required */
    RoleSessionName: 'RailsUser', /* required */
    WebIdentityToken: '<%= session[:token] %>', /* required */
    ProviderId: 'www.amazon.com'
  };
  var sts = new AWS.STS({apiVersion: '2011-06-15'});

    sts.assumeRoleWithWebIdentity(params, function(err, data) {
      if (err) console.log(err, err.stack); // an error occurred
      else {
        var akid = data.Credentials.AccessKeyId;
        var session = data.Credentials.SessionToken;
        var secret = data.Credentials.SecretAccessKey;

        $('input[name="AWSAccessKeyId"]').val(akid);
        $('input[name="x-amz-security-token"]').val(session);

        // yes someone could mess with the policy and sign it themselves
        // but the policy on the web federation role is very limited anyway
        var policy = $('#policy').val();
        $('input[name="signature"]').val(AWS.util.crypto.hmac(secret,policy,"base64","sha1"));

        var s3 = new AWS.S3({apiVersion: '2006-03-01', accessKeyId: akid, sessionToken: session, secretAccessKey: secret});

        var params = {
          Bucket: 'sayersr-demos-uploads', /* bucket shouldn't be hardcoded */
          Prefix: '<%= @upload.prefix %>'
        };
        s3.listObjects(params, function(err, data) {
          if (err) console.log(err, err.stack); // an error occurred
          else {
            console.log(data);
            $.each(data.Contents, function(k, v) {
              var name = v.Key.replace('<%= @upload.prefix %>', '')
              if (name!='') $('#files').append('<li>' + name + '</li>');
            });
          }
        });

      }
    });
  <% end %>
</script>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<div id="amazon-root"></div>
<script type="text/javascript">

  window.onAmazonLoginReady = function() {
    amazon.Login.setClientId('<%= ENV['AMAZON_CLIENT_ID'] %>');
  };
  (function(d) {
    var a = d.createElement('script'); a.type = 'text/javascript';
    a.async = true; a.id = 'amazon-login-sdk';
    a.src = 'https://api-cdn.amazon.com/sdk/login1.js';
    d.getElementById('amazon-root').appendChild(a);
  })(document);

</script>

<a href="#" id="LoginWithAmazon"><img border="0" alt="Login with Amazon"
    src="https://images-na.ssl-images-amazon.com/images/G/01/lwa/btnLWA_drkgry_156x32.png"
    width="156" height="32" /></a>

<a href="https://www.amazon.com/ap/oa/?client_id=<%= ENV['AMAZON_CLIENT_ID'] %>&scope=profile&response_type=code&redirect_uri=<%= callback_url(:provider => "amazon") %>">Non Javascript login</a>

<%
  s = "http://169.254.169.254/latest/meta-data/instance-id"
  uri = URI.parse(s)
  request = Net::HTTP::Get.new(uri.request_uri)
  #response = Net::HTTP.new(uri.host, uri.port).request(request)
  begin
    response = Net::HTTP.start(uri.host, uri.port) {|http|
      http.read_timeout = 1
      http.open_timeout = 1
      http.request(request)
    }
    concat("[#{response.body}]")
  rescue Net::ReadTimeout => e
    concat("[no metadata here]")
  end
%>
<p></p>

<form class="form-horizontal" role="form">
  <div class="form-group">
    <label class="col-sm-2 control-label">AccessKeyId</label>
    <div class="col-sm-6">
      <input type="text" class="form-control" name="AccessKeyId">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Expiration</label>
    <div class="col-sm-6">
      <input type="text" class="form-control" name="Expiration">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">SecretAccessKey</label>
    <div class="col-sm-6">
      <input type="text" class="form-control" name="SecretAccessKey">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">SessionToken</label>
    <div class="col-sm-6">
      <input type="text" class="form-control" name="SessionToken">
    </div>
  </div>
</form>

<script type="text/javascript">

  document.getElementById('LoginWithAmazon').onclick = function() {
    options = { scope : 'profile', response_type : 'code' };
    // http://stackoverflow.com/questions/9346695/what-is-the-link-to-path-to-a-non-resourceful-route
    amazon.Login.authorize(options, '<%= callback_url(:provider => "amazon") %>');
    return false;
  };

  var params = {
    RoleArn: 'arn:aws:iam::612895797421:role/ExtraTimeWebIdentity', /* required */
    RoleSessionName: 'RailsUser', /* required */
    WebIdentityToken: '<%= session[:token] %>', /* required */
    ProviderId: 'www.amazon.com'
  };
  var sts = new AWS.STS({apiVersion: '2011-06-15'});

<% if !session[:token].nil? %>
  sts.assumeRoleWithWebIdentity(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else {
      $('input[name="AccessKeyId"]').val(data.Credentials.AccessKeyId);
      $('input[name="Expiration"]').val(data.Credentials.Expiration);
      $('input[name="SecretAccessKey"]').val(data.Credentials.SecretAccessKey);
      $('input[name="SessionToken"]').val(data.Credentials.SessionToken);
    }
  });
<% end %>
</script>